version: 0.2
       
env:
  parameter-store:
    LOGIN_USERID: "docker-userid"
    LOGIN_PASSWORD: "docker-password"
    BUILD_JOBS: "docker-build-jobs"

phases:
  install:
    runtime-versions:
      Docker: 18
  pre_build:
    commands:
      - echo Logging into Docker Hub...
      - docker login -u $LOGIN_USERID -p $LOGIN_PASSWORD
  build:
    commands:
      - echo Start building latest evt builder...
      - cd Docker/builder && docker build . -t everitoken/builder:latest --build-arg bjobs=$BUILD_JOBS
  post_build:
    commands:
      - echo Publish to Docker Hub...
      - docker push everitoken/builder:latest
