version: 0.2

env:
  parameter-store:
    LOGIN_USERID: "docker-userid"
    LOGIN_PASSWORD: "docker-password"

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging into Docker Hub...
      - docker login -u $LOGIN_USERID -p $LOGIN_PASSWORD
  build:
    commands:
      - echo Start building latest pyjmzk Docker image...
      - cd Docker && docker build pyjmzk -t jmzkChain/pyjmzk:latest
  post_build:
    commands:
      - echo Publish to Docker Hub...
      - docker push jmzkChain/pyjmzk:latest
